#
# Makefile for the keyboard device drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_AMLOGIC_LEDSCREEN_TM1640)		+= tm1640.o
obj-$(CONFIG_AMLOGIC_LEDSCREEN_SN3112)		+= sn3112.o
