#
# Makefile for the sensor drivers.
#
obj-$(CONFIG_AMLOGIC_SENSOR_CY8C4014) 	+= cy8c4014.o
obj-$(CONFIG_AMLOGIC_G_SENSOR)			+= kionix_accel.o
obj-$(CONFIG_AMLOGIC_T_H_SENSOR)		+= shtc3.o
obj-$(CONFIG_AMLOGIC_L_P_SENSOR)		+= stk3311.o
obj-$(CONFIG_AMLOGIC_SENSOR_MIR3DA) += mir3da.o
mir3da-objs:= mir3da_cust.o mir3da_core.o
#obj-$(CONFIG_AMLOGIC_SENSOR_MIR3DA) += mir3da_core.o
#obj-$(CONFIG_AMLOGIC_SENSOR_MIR3DA) += mir3da_cust.o
